:tab_0:
  :value: 0
  :restore_default: false

:tab_0_0:
  :value: 0
  :restore_default: false

:tab_0_0_0:
  :value: 0
  :restore_default: false

:tab_0_0_1:
  :value: 0
  :restore_default: false

:tab_0_0_2:
  :value: 0
  :restore_default: false